In [3]:
import numpy as np
import pandas as pd

In [6]:
Netflix=pd.read_csv(r'/content/netflix.csv')
Netflix

                      title        director date_added     type
0               Alias Grace             NaN   3-Nov-17  TV Show
1            A Patch of Fog  Michael Lennox  15-Apr-17    Movie
2                  Lunatics             NaN  19-Apr-19  TV Show
3                 Uriyadi 2     Vijay Kumar   2-Aug-19    Movie
4         Shrek the Musical     Jason Moore  29-Dec-13    Movie
...                     ...             ...        ...      ...
5832            The Pursuit     John Papola   7-Aug-19    Movie
5833       Hurricane Bianca   Matt Kugelman   1-Jan-17    Movie
5834           Amar's Hands  Khaled Youssef  26-Apr-19    Movie
5835  Bill Nye: Science Guy  Jason Sussberg  25-Apr-18    Movie
5836           Age of Glory             NaN        NaN  TV Show

[5837 rows x 4 columns]

In [7]:
Netflix.head()

               title        director date_added     type
0        Alias Grace             NaN   3-Nov-17  TV Show
1     A Patch of Fog  Michael Lennox  15-Apr-17    Movie
2           Lunatics             NaN  19-Apr-19  TV Show
3          Uriyadi 2     Vijay Kumar   2-Aug-19    Movie
4  Shrek the Musical     Jason Moore  29-Dec-13    Movie

In [8]:
Netflix.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5837 entries, 0 to 5836
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   title       5837 non-null   object
 1   director    3936 non-null   object
 2   date_added  5195 non-null   object
 3   type        5837 non-null   object
dtypes: object(4)
memory usage: 182.5+ KB

In [9]:
Netflix.title.astype('category')

0                 Alias Grace
1              A Patch of Fog
2                    Lunatics
3                   Uriyadi 2
4           Shrek the Musical
                ...
5832              The Pursuit
5833         Hurricane Bianca
5834             Amar's Hands
5835    Bill Nye: Science Guy
5836             Age of Glory
Name: title, Length: 5837, dtype: category
Categories (5780, object): ['#Roxy', '#Rucker50', '#Selfie', '#Selfie 69', ..., '海的儿子', '마녀사냥',
                            '반드시 잡는다', '최강전사 미니특공대 : 영웅의 탄생']

In [10]:
Netflix.director.astype('category')

0                  NaN
1       Michael Lennox
2                  NaN
3          Vijay Kumar
4          Jason Moore
             ...
5832       John Papola
5833     Matt Kugelman
5834    Khaled Youssef
5835    Jason Sussberg
5836               NaN
Name: director, Length: 5837, dtype: category
Categories (3024, object): ['A. L. Vijay', 'A. Salaam', 'A.R. Murugadoss', 'Aadish Keluskar', ...,
                            'Ísold Uggadóttir', 'Óskar Thór Axelsson', 'Ömer Faruk Sorak',
                            'Şenol Sönmez']

In [11]:
Netflix['date_added']=pd.to_datetime(Netflix['date_added'])
Netflix['date_added']

/tmp/ipykernel_1656/1289893523.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  Netflix['date_added']=pd.to_datetime(Netflix['date_added'])

0      2017-11-03
1      2017-04-15
2      2019-04-19
3      2019-08-02
4      2013-12-29
          ...
5832   2019-08-07
5833   2017-01-01
5834   2019-04-26
5835   2018-04-25
5836          NaT
Name: date_added, Length: 5837, dtype: datetime64[ns]

In [12]:
Netflix.type.astype('category')

0       TV Show
1         Movie
2       TV Show
3         Movie
4         Movie
         ...
5832      Movie
5833      Movie
5834      Movie
5835      Movie
5836    TV Show
Name: type, Length: 5837, dtype: category
Categories (2, object): ['Movie', 'TV Show']

In [13]:
Netflix.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5837 entries, 0 to 5836
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   title       5837 non-null   object
 1   director    3936 non-null   object
 2   date_added  5195 non-null   datetime64[ns]
 3   type        5837 non-null   object
dtypes: datetime64[ns](1), object(3)
memory usage: 182.5+ KB

In [14]:
Netflix[['title','type','director']]=Netflix[['title','type','director']].astype('category')
Netflix[['title','type','director']]

                      title     type        director
0               Alias Grace  TV Show             NaN
1            A Patch of Fog    Movie  Michael Lennox
2                  Lunatics  TV Show             NaN
3                 Uriyadi 2    Movie     Vijay Kumar
4         Shrek the Musical    Movie     Jason Moore
...                     ...      ...             ...
5832            The Pursuit    Movie     John Papola
5833       Hurricane Bianca    Movie   Matt Kugelman
5834           Amar's Hands    Movie  Khaled Youssef
5835  Bill Nye: Science Guy    Movie  Jason Sussberg
5836           Age of Glory  TV Show             NaN

[5837 rows x 3 columns]

In [15]:
Netflix.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5837 entries, 0 to 5836
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   title       5837 non-null   category
 1   director    3936 non-null   category
 2   date_added  5195 non-null   datetime64[ns]
 3   type        5837 non-null   category
dtypes: category(3), datetime64[ns](1)
memory usage: 336.7 KB

In [16]:
Netflix[['title','director']]=Netflix[['title','director']].astype('string')
Netflix[['title','director']]

                      title        director
0               Alias Grace            <NA>
1            A Patch of Fog  Michael Lennox
2                  Lunatics            <NA>
3                 Uriyadi 2     Vijay Kumar
4         Shrek the Musical     Jason Moore
...                     ...             ...
5832            The Pursuit     John Papola
5833       Hurricane Bianca   Matt Kugelman
5834           Amar's Hands  Khaled Youssef
5835  Bill Nye: Science Guy  Jason Sussberg
5836           Age of Glory            <NA>

[5837 rows x 2 columns]

**1.Optimize the data set for limited memory use and maximum utility.**

In [17]:
Netflix.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5837 entries, 0 to 5836
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   title       5837 non-null   string
 1   director    3936 non-null   string
 2   date_added  5195 non-null   datetime64[ns]
 3   type        5837 non-null   category
dtypes: category(1), datetime64[ns](1), string(2)
memory usage: 142.8 KB

In [18]:
Netflix.nunique()

title         5780
director      3024
date_added    1092
type             2
dtype: int64

In [19]:
Netflix.title.nunique()

5780

In [20]:
Netflix.isnull().sum()

title            0
director      1901
date_added     642
type             0
dtype: int64

In [21]:
Netflix["director"] = Netflix["director"].fillna("Unknown")
Netflix["date_added"] = Netflix["date_added"].fillna(pd.Timestamp("1900-01-01"))
print(Netflix["director"])
print(Netflix["date_added"])

0              Unknown
1       Michael Lennox
2              Unknown
3          Vijay Kumar
4          Jason Moore
             ...
5832       John Papola
5833     Matt Kugelman
5834    Khaled Youssef
5835    Jason Sussberg
5836           Unknown
Name: director, Length: 5837, dtype: string
0      2017-11-03
1      2017-04-15
2      2019-04-19
3      2019-08-02
4      2013-12-29
          ...
5832   2019-08-07
5833   2017-01-01
5834   2019-04-26
5835   2018-04-25
5836   1900-01-01
Name: date_added, Length: 5837, dtype: datetime64[ns]

In [22]:
Netflix.isnull().any()

title         False
director      False
date_added    False
type          False
dtype: bool

In [23]:
Netflix.isnull().all()

title         False
director      False
date_added    False
type          False
dtype: bool

In [24]:
Netflix.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5837 entries, 0 to 5836
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   title       5837 non-null   string
 1   director    5837 non-null   string
 2   date_added  5837 non-null   datetime64[ns]
 3   type        5837 non-null   category
dtypes: category(1), datetime64[ns](1), string(2)
memory usage: 142.8 KB

2.Find all rows with a title of "Limitless"

In [25]:
Netflix[Netflix['title']=='Limitless']

          title         director date_added     type
1559  Limitless      Neil Burger 2019-05-16    Movie
2564  Limitless          Unknown 2016-07-01  TV Show
4579  Limitless  Vrinda Samartha 2019-10-01    Movie

3.Find all rows with a director of "Robert Rodriguez" and a type of "Movie".

In [26]:
Netflix[(Netflix['director']=='Robert Rodriguez')& (Netflix['type']=='Movie')]

,title,director,date_added,type
1384,Spy Kids: All the Time in the World,Robert Rodriguez,2019-02-19,Movie
1416,Spy Kids 3: Game Over,Robert Rodriguez,2019-04-01,Movie
1460,Spy Kids 2: The Island of Lost Dreams,Robert Rodriguez,2019-03-08,Movie
2890,Sin City,Robert Rodriguez,2019-10-01,Movie
3836,Shorts,Robert Rodriguez,2019-07-01,Movie
3883,Spy Kids,Robert Rodriguez,2019-04-01,Movie

4.Find all rows with either a date_added of "2019-07-31" or a director of "Robert Altman".

In [27]:
Netflix[(Netflix['date_added']=='2019-07-31')|(Netflix['director']=='Robert Altman')]

                                title       director date_added     type
611                            Popeye  Robert Altman 2019-11-24    Movie
1028        The Red Sea Diving Resort    Gideon Raff 2019-07-31    Movie
1092                     Gosford Park  Robert Altman 2019-11-01    Movie
3473  Bangkok Love Stories: Innocence        Unknown 2019-07-31  TV Show
5117                       Ramen Shop      Eric Khoo 2019-07-31    Movie

5.Find all rows with a director of "Orson Welles", "Aditya Kripalani", or "Sam Raimi".

In [28]:
Netflix[(Netflix['director']=='Orson Welles')|(Netflix['director']=='Aditya Kripalani')|(Netflix['director']=='Sam Raimi')]

                           title          director date_added   type
946                 The Stranger      Orson Welles 2018-07-19  Movie
1870                    The Gift         Sam Raimi 2019-11-20  Movie
3706                Spider-Man 3         Sam Raimi 2019-11-01  Movie
4243        Tikli and Laxmi Bomb  Aditya Kripalani 2018-08-01  Movie
4475  The Other Side of the Wind      Orson Welles 2018-11-02  Movie
5115    Tottaa Pataaka Item Maal  Aditya Kripalani 2019-06-25  Movie

6.Find all rows with a date_added value between May 1, 2019 and June 1, 2019.

In [29]:
Netflix[Netflix['date_added'].between('2019-05-01','2019-06-01')]

,title,director,date_added,type
29,Chopsticks,Sachin Yardi,2019-05-31,Movie
60,Away From Home,Unknown,2019-05-08,TV Show
82,III Smoking Barrels,Sanjib Dey,2019-06-01,Movie
108,Jailbirds,Unknown,2019-05-10,TV Show
124,Pegasus,Han Han,2019-05-31,Movie
...,...,...,...,...
5671,Satan & Adam,V. Scott Balcerek,2019-06-01,Movie
5675,Rim of the World,McG,2019-05-24,Movie
5677,Malibu Rescue,Savage Steve Holland,2019-05-13,Movie
5739,Mission Istaanbul: Darr Ke Aagey Jeet Hai,Apoorva Lakhia,2019-05-16,Movie
5829,The Kindness Diaries,Unknown,2019-05-01,TV Show

7.Drop all rows with a NaN value in the director column.

In [30]:
Netflix.dropna(subset=['director'])

                      title        director date_added     type
0               Alias Grace         Unknown 2017-11-03  TV Show
1            A Patch of Fog  Michael Lennox 2017-04-15    Movie
2                  Lunatics         Unknown 2019-04-19  TV Show
3                 Uriyadi 2     Vijay Kumar 2019-08-02    Movie
4         Shrek the Musical     Jason Moore 2013-12-29    Movie
...                     ...             ...        ...      ...
5832            The Pursuit     John Papola 2019-08-07    Movie
5833       Hurricane Bianca   Matt Kugelman 2017-01-01    Movie
5834           Amar's Hands  Khaled Youssef 2019-04-26    Movie
5835  Bill Nye: Science Guy  Jason Sussberg 2018-04-25    Movie
5836           Age of Glory         Unknown 1900-01-01  TV Show

[5837 rows x 4 columns]

8.Identify the days when Netflix added only one movie to its catalog.

In [31]:
movies = Netflix[Netflix['type'] == 'Movie']
movie_counts = movies['date_added'].value_counts()
single_movie_days = movie_counts[movie_counts == 1]
single_movie_days

date_added
2019-04-22    1
2017-05-31    1
2018-02-04    1
2017-11-11    1
2017-12-25    1
             ..
2018-09-27    1
2016-03-09    1
2018-03-04    1
2018-06-19    1
2017-07-20    1
Name: count, Length: 426, dtype: int64